// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.5
// source: plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginService_GetInfo_FullMethodName       = "/airgate.plugin.v1.PluginService/GetInfo"
	PluginService_Init_FullMethodName          = "/airgate.plugin.v1.PluginService/Init"
	PluginService_Start_FullMethodName         = "/airgate.plugin.v1.PluginService/Start"
	PluginService_Stop_FullMethodName          = "/airgate.plugin.v1.PluginService/Stop"
	PluginService_GetWebAssets_FullMethodName  = "/airgate.plugin.v1.PluginService/GetWebAssets"
	PluginService_HealthCheck_FullMethodName   = "/airgate.plugin.v1.PluginService/HealthCheck"
	PluginService_HandleRequest_FullMethodName = "/airgate.plugin.v1.PluginService/HandleRequest"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginServiceClient interface {
	GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfoResponse, error)
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*Empty, error)
	Start(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// 获取插件的前端静态资源
	GetWebAssets(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WebAssetsResponse, error)
	// 健康检查（可选，插件未实现时返回成功）
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// 通用请求代理：Core 透传，插件自行路由（可选，插件未实现时返回 501）
	HandleRequest(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfoResponse)
	err := c.cc.Invoke(ctx, PluginService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PluginService_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Start(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PluginService_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PluginService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) GetWebAssets(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WebAssetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebAssetsResponse)
	err := c.cc.Invoke(ctx, PluginService_GetWebAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PluginService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) HandleRequest(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HttpResponse)
	err := c.cc.Invoke(ctx, PluginService_HandleRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility.
type PluginServiceServer interface {
	GetInfo(context.Context, *Empty) (*PluginInfoResponse, error)
	Init(context.Context, *InitRequest) (*Empty, error)
	Start(context.Context, *Empty) (*Empty, error)
	Stop(context.Context, *Empty) (*Empty, error)
	// 获取插件的前端静态资源
	GetWebAssets(context.Context, *Empty) (*WebAssetsResponse, error)
	// 健康检查（可选，插件未实现时返回成功）
	HealthCheck(context.Context, *Empty) (*Empty, error)
	// 通用请求代理：Core 透传，插件自行路由（可选，插件未实现时返回 501）
	HandleRequest(context.Context, *HttpRequest) (*HttpResponse, error)
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServiceServer struct{}

func (UnimplementedPluginServiceServer) GetInfo(context.Context, *Empty) (*PluginInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedPluginServiceServer) Init(context.Context, *InitRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedPluginServiceServer) Start(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedPluginServiceServer) Stop(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedPluginServiceServer) GetWebAssets(context.Context, *Empty) (*WebAssetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWebAssets not implemented")
}
func (UnimplementedPluginServiceServer) HealthCheck(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPluginServiceServer) HandleRequest(context.Context, *HttpRequest) (*HttpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleRequest not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}
func (UnimplementedPluginServiceServer) testEmbeddedByValue()                       {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Start(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_GetWebAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetWebAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetWebAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetWebAssets(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_HandleRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).HandleRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_HandleRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).HandleRequest(ctx, req.(*HttpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "airgate.plugin.v1.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _PluginService_GetInfo_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _PluginService_Init_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _PluginService_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _PluginService_Stop_Handler,
		},
		{
			MethodName: "GetWebAssets",
			Handler:    _PluginService_GetWebAssets_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PluginService_HealthCheck_Handler,
		},
		{
			MethodName: "HandleRequest",
			Handler:    _PluginService_HandleRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	GatewayService_GetPlatform_FullMethodName     = "/airgate.plugin.v1.GatewayService/GetPlatform"
	GatewayService_GetModels_FullMethodName       = "/airgate.plugin.v1.GatewayService/GetModels"
	GatewayService_GetRoutes_FullMethodName       = "/airgate.plugin.v1.GatewayService/GetRoutes"
	GatewayService_Forward_FullMethodName         = "/airgate.plugin.v1.GatewayService/Forward"
	GatewayService_ForwardStream_FullMethodName   = "/airgate.plugin.v1.GatewayService/ForwardStream"
	GatewayService_ValidateAccount_FullMethodName = "/airgate.plugin.v1.GatewayService/ValidateAccount"
	GatewayService_QueryQuota_FullMethodName      = "/airgate.plugin.v1.GatewayService/QueryQuota"
	GatewayService_HandleWebSocket_FullMethodName = "/airgate.plugin.v1.GatewayService/HandleWebSocket"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayServiceClient interface {
	GetPlatform(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error)
	GetModels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModelsResponse, error)
	GetRoutes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RoutesResponse, error)
	Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardOutcome, error)
	ForwardStream(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ForwardChunk], error)
	ValidateAccount(ctx context.Context, in *CredentialsRequest, opts ...grpc.CallOption) (*Empty, error)
	QueryQuota(ctx context.Context, in *CredentialsRequest, opts ...grpc.CallOption) (*QuotaInfoResponse, error)
	// WebSocket 双向流
	HandleWebSocket(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WebSocketFrame, WebSocketFrame], error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) GetPlatform(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetPlatform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetModels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelsResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetRoutes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutesResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardOutcome, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardOutcome)
	err := c.cc.Invoke(ctx, GatewayService_Forward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ForwardStream(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ForwardChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayService_ServiceDesc.Streams[0], GatewayService_ForwardStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ForwardRequest, ForwardChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_ForwardStreamClient = grpc.ServerStreamingClient[ForwardChunk]

func (c *gatewayServiceClient) ValidateAccount(ctx context.Context, in *CredentialsRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GatewayService_ValidateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) QueryQuota(ctx context.Context, in *CredentialsRequest, opts ...grpc.CallOption) (*QuotaInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuotaInfoResponse)
	err := c.cc.Invoke(ctx, GatewayService_QueryQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) HandleWebSocket(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WebSocketFrame, WebSocketFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayService_ServiceDesc.Streams[1], GatewayService_HandleWebSocket_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WebSocketFrame, WebSocketFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_HandleWebSocketClient = grpc.BidiStreamingClient[WebSocketFrame, WebSocketFrame]

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
type GatewayServiceServer interface {
	GetPlatform(context.Context, *Empty) (*StringResponse, error)
	GetModels(context.Context, *Empty) (*ModelsResponse, error)
	GetRoutes(context.Context, *Empty) (*RoutesResponse, error)
	Forward(context.Context, *ForwardRequest) (*ForwardOutcome, error)
	ForwardStream(*ForwardRequest, grpc.ServerStreamingServer[ForwardChunk]) error
	ValidateAccount(context.Context, *CredentialsRequest) (*Empty, error)
	QueryQuota(context.Context, *CredentialsRequest) (*QuotaInfoResponse, error)
	// WebSocket 双向流
	HandleWebSocket(grpc.BidiStreamingServer[WebSocketFrame, WebSocketFrame]) error
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) GetPlatform(context.Context, *Empty) (*StringResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlatform not implemented")
}
func (UnimplementedGatewayServiceServer) GetModels(context.Context, *Empty) (*ModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModels not implemented")
}
func (UnimplementedGatewayServiceServer) GetRoutes(context.Context, *Empty) (*RoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoutes not implemented")
}
func (UnimplementedGatewayServiceServer) Forward(context.Context, *ForwardRequest) (*ForwardOutcome, error) {
	return nil, status.Error(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedGatewayServiceServer) ForwardStream(*ForwardRequest, grpc.ServerStreamingServer[ForwardChunk]) error {
	return status.Error(codes.Unimplemented, "method ForwardStream not implemented")
}
func (UnimplementedGatewayServiceServer) ValidateAccount(context.Context, *CredentialsRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateAccount not implemented")
}
func (UnimplementedGatewayServiceServer) QueryQuota(context.Context, *CredentialsRequest) (*QuotaInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryQuota not implemented")
}
func (UnimplementedGatewayServiceServer) HandleWebSocket(grpc.BidiStreamingServer[WebSocketFrame, WebSocketFrame]) error {
	return status.Error(codes.Unimplemented, "method HandleWebSocket not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_GetPlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetPlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetPlatform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetPlatform(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetModels(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetRoutes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_Forward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).Forward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_Forward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).Forward(ctx, req.(*ForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ForwardStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ForwardRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayServiceServer).ForwardStream(m, &grpc.GenericServerStream[ForwardRequest, ForwardChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_ForwardStreamServer = grpc.ServerStreamingServer[ForwardChunk]

func _GatewayService_ValidateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ValidateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ValidateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ValidateAccount(ctx, req.(*CredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_QueryQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).QueryQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_QueryQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).QueryQuota(ctx, req.(*CredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_HandleWebSocket_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayServiceServer).HandleWebSocket(&grpc.GenericServerStream[WebSocketFrame, WebSocketFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_HandleWebSocketServer = grpc.BidiStreamingServer[WebSocketFrame, WebSocketFrame]

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "airgate.plugin.v1.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlatform",
			Handler:    _GatewayService_GetPlatform_Handler,
		},
		{
			MethodName: "GetModels",
			Handler:    _GatewayService_GetModels_Handler,
		},
		{
			MethodName: "GetRoutes",
			Handler:    _GatewayService_GetRoutes_Handler,
		},
		{
			MethodName: "Forward",
			Handler:    _GatewayService_Forward_Handler,
		},
		{
			MethodName: "ValidateAccount",
			Handler:    _GatewayService_ValidateAccount_Handler,
		},
		{
			MethodName: "QueryQuota",
			Handler:    _GatewayService_QueryQuota_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ForwardStream",
			Handler:       _GatewayService_ForwardStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "HandleWebSocket",
			Handler:       _GatewayService_HandleWebSocket_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

const (
	ExtensionService_Migrate_FullMethodName             = "/airgate.plugin.v1.ExtensionService/Migrate"
	ExtensionService_GetBackgroundTasks_FullMethodName  = "/airgate.plugin.v1.ExtensionService/GetBackgroundTasks"
	ExtensionService_RunBackgroundTask_FullMethodName   = "/airgate.plugin.v1.ExtensionService/RunBackgroundTask"
	ExtensionService_HandleRequest_FullMethodName       = "/airgate.plugin.v1.ExtensionService/HandleRequest"
	ExtensionService_HandleStreamRequest_FullMethodName = "/airgate.plugin.v1.ExtensionService/HandleStreamRequest"
)

// ExtensionServiceClient is the client API for ExtensionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExtensionServiceClient interface {
	Migrate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	GetBackgroundTasks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BackgroundTasksResponse, error)
	// 由 Core 调度器按 Interval 周期触发；插件进程内查表执行 Handler
	RunBackgroundTask(ctx context.Context, in *RunBackgroundTaskRequest, opts ...grpc.CallOption) (*Empty, error)
	// HTTP 请求由核心代理到插件
	HandleRequest(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error)
	HandleStreamRequest(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HttpResponseChunk], error)
}

type extensionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExtensionServiceClient(cc grpc.ClientConnInterface) ExtensionServiceClient {
	return &extensionServiceClient{cc}
}

func (c *extensionServiceClient) Migrate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ExtensionService_Migrate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) GetBackgroundTasks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BackgroundTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackgroundTasksResponse)
	err := c.cc.Invoke(ctx, ExtensionService_GetBackgroundTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) RunBackgroundTask(ctx context.Context, in *RunBackgroundTaskRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ExtensionService_RunBackgroundTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) HandleRequest(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HttpResponse)
	err := c.cc.Invoke(ctx, ExtensionService_HandleRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) HandleStreamRequest(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HttpResponseChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExtensionService_ServiceDesc.Streams[0], ExtensionService_HandleStreamRequest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HttpRequest, HttpResponseChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExtensionService_HandleStreamRequestClient = grpc.ServerStreamingClient[HttpResponseChunk]

// ExtensionServiceServer is the server API for ExtensionService service.
// All implementations must embed UnimplementedExtensionServiceServer
// for forward compatibility.
type ExtensionServiceServer interface {
	Migrate(context.Context, *Empty) (*Empty, error)
	GetBackgroundTasks(context.Context, *Empty) (*BackgroundTasksResponse, error)
	// 由 Core 调度器按 Interval 周期触发；插件进程内查表执行 Handler
	RunBackgroundTask(context.Context, *RunBackgroundTaskRequest) (*Empty, error)
	// HTTP 请求由核心代理到插件
	HandleRequest(context.Context, *HttpRequest) (*HttpResponse, error)
	HandleStreamRequest(*HttpRequest, grpc.ServerStreamingServer[HttpResponseChunk]) error
	mustEmbedUnimplementedExtensionServiceServer()
}

// UnimplementedExtensionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExtensionServiceServer struct{}

func (UnimplementedExtensionServiceServer) Migrate(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Migrate not implemented")
}
func (UnimplementedExtensionServiceServer) GetBackgroundTasks(context.Context, *Empty) (*BackgroundTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBackgroundTasks not implemented")
}
func (UnimplementedExtensionServiceServer) RunBackgroundTask(context.Context, *RunBackgroundTaskRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RunBackgroundTask not implemented")
}
func (UnimplementedExtensionServiceServer) HandleRequest(context.Context, *HttpRequest) (*HttpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleRequest not implemented")
}
func (UnimplementedExtensionServiceServer) HandleStreamRequest(*HttpRequest, grpc.ServerStreamingServer[HttpResponseChunk]) error {
	return status.Error(codes.Unimplemented, "method HandleStreamRequest not implemented")
}
func (UnimplementedExtensionServiceServer) mustEmbedUnimplementedExtensionServiceServer() {}
func (UnimplementedExtensionServiceServer) testEmbeddedByValue()                          {}

// UnsafeExtensionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtensionServiceServer will
// result in compilation errors.
type UnsafeExtensionServiceServer interface {
	mustEmbedUnimplementedExtensionServiceServer()
}

func RegisterExtensionServiceServer(s grpc.ServiceRegistrar, srv ExtensionServiceServer) {
	// If the following call panics, it indicates UnimplementedExtensionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExtensionService_ServiceDesc, srv)
}

func _ExtensionService_Migrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).Migrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_Migrate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).Migrate(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_GetBackgroundTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).GetBackgroundTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_GetBackgroundTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).GetBackgroundTasks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_RunBackgroundTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunBackgroundTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).RunBackgroundTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_RunBackgroundTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).RunBackgroundTask(ctx, req.(*RunBackgroundTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_HandleRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).HandleRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_HandleRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).HandleRequest(ctx, req.(*HttpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_HandleStreamRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HttpRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExtensionServiceServer).HandleStreamRequest(m, &grpc.GenericServerStream[HttpRequest, HttpResponseChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExtensionService_HandleStreamRequestServer = grpc.ServerStreamingServer[HttpResponseChunk]

// ExtensionService_ServiceDesc is the grpc.ServiceDesc for ExtensionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExtensionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "airgate.plugin.v1.ExtensionService",
	HandlerType: (*ExtensionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Migrate",
			Handler:    _ExtensionService_Migrate_Handler,
		},
		{
			MethodName: "GetBackgroundTasks",
			Handler:    _ExtensionService_GetBackgroundTasks_Handler,
		},
		{
			MethodName: "RunBackgroundTask",
			Handler:    _ExtensionService_RunBackgroundTask_Handler,
		},
		{
			MethodName: "HandleRequest",
			Handler:    _ExtensionService_HandleRequest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HandleStreamRequest",
			Handler:       _ExtensionService_HandleStreamRequest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

const (
	MiddlewareService_OnForwardBegin_FullMethodName = "/airgate.plugin.v1.MiddlewareService/OnForwardBegin"
	MiddlewareService_OnForwardEnd_FullMethodName   = "/airgate.plugin.v1.MiddlewareService/OnForwardEnd"
)

// MiddlewareServiceClient is the client API for MiddlewareService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== 中间件服务（Core → Plugin，forward 路径拦截） ====================
//
// MiddlewareService 让"请求中间层"这种旁路插件能拿到每次 forward 的前后事件：
//   - OnForwardBegin  — 选完账号 / 还没调 upstream 之前，能改 headers / 拒绝请求
//   - OnForwardEnd    — upstream 返回之后 / 写 usage_log 之前，拿到完整 metadata
//
// 设计原则（详见 ADR-0001 Decision 2/3）：
//  1. middleware 挂了不能 block 生产：返回 error 只 log warn，流程继续；
//     只有 OnForwardBegin 明确返回 Action=DENY 才会拒绝请求
//  2. 多个 middleware 按 priority 排序。Begin 升序、End 降序（LIFO）
//  3. payload 两段式：默认只传元数据，声明 middleware.read_body capability 的插件
//     才会收到 request_body / response_body
//  4. 流式响应的 response_body 只给摘要（首次非空 chunk 拼装），完整流式内容留给
//     未来的 OnStreamChunk（ADR-0002）
//
// 新角色：middleware 插件不是 gateway（不替代 upstream），也不是 extension
// （不跑后台任务 + 自定义 HTTP）。它在 PluginInfo.type = "middleware" 中声明。
type MiddlewareServiceClient interface {
	OnForwardBegin(ctx context.Context, in *MiddlewareRequest, opts ...grpc.CallOption) (*MiddlewareDecision, error)
	OnForwardEnd(ctx context.Context, in *MiddlewareEvent, opts ...grpc.CallOption) (*Empty, error)
}

type middlewareServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMiddlewareServiceClient(cc grpc.ClientConnInterface) MiddlewareServiceClient {
	return &middlewareServiceClient{cc}
}

func (c *middlewareServiceClient) OnForwardBegin(ctx context.Context, in *MiddlewareRequest, opts ...grpc.CallOption) (*MiddlewareDecision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MiddlewareDecision)
	err := c.cc.Invoke(ctx, MiddlewareService_OnForwardBegin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareServiceClient) OnForwardEnd(ctx context.Context, in *MiddlewareEvent, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MiddlewareService_OnForwardEnd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiddlewareServiceServer is the server API for MiddlewareService service.
// All implementations must embed UnimplementedMiddlewareServiceServer
// for forward compatibility.
//
// ==================== 中间件服务（Core → Plugin，forward 路径拦截） ====================
//
// MiddlewareService 让"请求中间层"这种旁路插件能拿到每次 forward 的前后事件：
//   - OnForwardBegin  — 选完账号 / 还没调 upstream 之前，能改 headers / 拒绝请求
//   - OnForwardEnd    — upstream 返回之后 / 写 usage_log 之前，拿到完整 metadata
//
// 设计原则（详见 ADR-0001 Decision 2/3）：
//  1. middleware 挂了不能 block 生产：返回 error 只 log warn，流程继续；
//     只有 OnForwardBegin 明确返回 Action=DENY 才会拒绝请求
//  2. 多个 middleware 按 priority 排序。Begin 升序、End 降序（LIFO）
//  3. payload 两段式：默认只传元数据，声明 middleware.read_body capability 的插件
//     才会收到 request_body / response_body
//  4. 流式响应的 response_body 只给摘要（首次非空 chunk 拼装），完整流式内容留给
//     未来的 OnStreamChunk（ADR-0002）
//
// 新角色：middleware 插件不是 gateway（不替代 upstream），也不是 extension
// （不跑后台任务 + 自定义 HTTP）。它在 PluginInfo.type = "middleware" 中声明。
type MiddlewareServiceServer interface {
	OnForwardBegin(context.Context, *MiddlewareRequest) (*MiddlewareDecision, error)
	OnForwardEnd(context.Context, *MiddlewareEvent) (*Empty, error)
	mustEmbedUnimplementedMiddlewareServiceServer()
}

// UnimplementedMiddlewareServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMiddlewareServiceServer struct{}

func (UnimplementedMiddlewareServiceServer) OnForwardBegin(context.Context, *MiddlewareRequest) (*MiddlewareDecision, error) {
	return nil, status.Error(codes.Unimplemented, "method OnForwardBegin not implemented")
}
func (UnimplementedMiddlewareServiceServer) OnForwardEnd(context.Context, *MiddlewareEvent) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnForwardEnd not implemented")
}
func (UnimplementedMiddlewareServiceServer) mustEmbedUnimplementedMiddlewareServiceServer() {}
func (UnimplementedMiddlewareServiceServer) testEmbeddedByValue()                           {}

// UnsafeMiddlewareServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MiddlewareServiceServer will
// result in compilation errors.
type UnsafeMiddlewareServiceServer interface {
	mustEmbedUnimplementedMiddlewareServiceServer()
}

func RegisterMiddlewareServiceServer(s grpc.ServiceRegistrar, srv MiddlewareServiceServer) {
	// If the following call panics, it indicates UnimplementedMiddlewareServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MiddlewareService_ServiceDesc, srv)
}

func _MiddlewareService_OnForwardBegin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MiddlewareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewareServiceServer).OnForwardBegin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiddlewareService_OnForwardBegin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewareServiceServer).OnForwardBegin(ctx, req.(*MiddlewareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiddlewareService_OnForwardEnd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MiddlewareEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewareServiceServer).OnForwardEnd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiddlewareService_OnForwardEnd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewareServiceServer).OnForwardEnd(ctx, req.(*MiddlewareEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// MiddlewareService_ServiceDesc is the grpc.ServiceDesc for MiddlewareService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MiddlewareService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "airgate.plugin.v1.MiddlewareService",
	HandlerType: (*MiddlewareServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnForwardBegin",
			Handler:    _MiddlewareService_OnForwardBegin_Handler,
		},
		{
			MethodName: "OnForwardEnd",
			Handler:    _MiddlewareService_OnForwardEnd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	HostService_SelectAccount_FullMethodName       = "/airgate.plugin.v1.HostService/SelectAccount"
	HostService_ReportAccountResult_FullMethodName = "/airgate.plugin.v1.HostService/ReportAccountResult"
	HostService_ProbeForward_FullMethodName        = "/airgate.plugin.v1.HostService/ProbeForward"
	HostService_Forward_FullMethodName             = "/airgate.plugin.v1.HostService/Forward"
	HostService_ForwardStream_FullMethodName       = "/airgate.plugin.v1.HostService/ForwardStream"
	HostService_ListGroups_FullMethodName          = "/airgate.plugin.v1.HostService/ListGroups"
	HostService_ListPlatforms_FullMethodName       = "/airgate.plugin.v1.HostService/ListPlatforms"
	HostService_ListModels_FullMethodName          = "/airgate.plugin.v1.HostService/ListModels"
	HostService_GetUserInfo_FullMethodName         = "/airgate.plugin.v1.HostService/GetUserInfo"
)

// HostServiceClient is the client API for HostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostServiceClient interface {
	// 选号：根据 (group_id, model) 走和真实用户请求完全相同的调度路径。
	SelectAccount(ctx context.Context, in *HostSelectAccountRequest, opts ...grpc.CallOption) (*HostSelectAccountResponse, error)
	// 把账号调用结果反馈给 scheduler 的失败计数器/状态机。
	ReportAccountResult(ctx context.Context, in *HostReportAccountResultRequest, opts ...grpc.CallOption) (*Empty, error)
	// 黑盒探测：内部组装一次最小的 chat completion 请求并直接执行。
	// 跳过 usage_log 写入、跳过用户余额扣款，仍然 ReportResult 反哺账号状态机。
	ProbeForward(ctx context.Context, in *HostProbeForwardRequest, opts ...grpc.CallOption) (*HostProbeForwardResponse, error)
	// 非流式业务转发：走完整管线（调度 → 网关插件 → 计费 → usage_log）。
	// 调用方需提供 user_id + group_id 以确定计费主体和调度路径。
	Forward(ctx context.Context, in *HostForwardRequest, opts ...grpc.CallOption) (*HostForwardResponse, error)
	// 流式业务转发：与 Forward 相同管线，结果通过 server stream 逐块返回。
	// 最后一块 done=true 携带 usage 信息（计费已在 Core 侧完成）。
	ForwardStream(ctx context.Context, in *HostForwardRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HostForwardChunk], error)
	// 列出所有分组。
	ListGroups(ctx context.Context, in *HostListGroupsRequest, opts ...grpc.CallOption) (*HostListGroupsResponse, error)
	// 列出已加载的网关平台（每个 gateway 插件对应一个 platform）。
	ListPlatforms(ctx context.Context, in *HostListPlatformsRequest, opts ...grpc.CallOption) (*HostListPlatformsResponse, error)
	// 列出指定平台的模型列表。
	ListModels(ctx context.Context, in *HostListModelsRequest, opts ...grpc.CallOption) (*HostListModelsResponse, error)
	// 获取用户基本信息（余额、角色、状态）。
	GetUserInfo(ctx context.Context, in *HostGetUserInfoRequest, opts ...grpc.CallOption) (*HostGetUserInfoResponse, error)
}

type hostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostServiceClient(cc grpc.ClientConnInterface) HostServiceClient {
	return &hostServiceClient{cc}
}

func (c *hostServiceClient) SelectAccount(ctx context.Context, in *HostSelectAccountRequest, opts ...grpc.CallOption) (*HostSelectAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostSelectAccountResponse)
	err := c.cc.Invoke(ctx, HostService_SelectAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) ReportAccountResult(ctx context.Context, in *HostReportAccountResultRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostService_ReportAccountResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) ProbeForward(ctx context.Context, in *HostProbeForwardRequest, opts ...grpc.CallOption) (*HostProbeForwardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostProbeForwardResponse)
	err := c.cc.Invoke(ctx, HostService_ProbeForward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) Forward(ctx context.Context, in *HostForwardRequest, opts ...grpc.CallOption) (*HostForwardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostForwardResponse)
	err := c.cc.Invoke(ctx, HostService_Forward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) ForwardStream(ctx context.Context, in *HostForwardRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HostForwardChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HostService_ServiceDesc.Streams[0], HostService_ForwardStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HostForwardRequest, HostForwardChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostService_ForwardStreamClient = grpc.ServerStreamingClient[HostForwardChunk]

func (c *hostServiceClient) ListGroups(ctx context.Context, in *HostListGroupsRequest, opts ...grpc.CallOption) (*HostListGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostListGroupsResponse)
	err := c.cc.Invoke(ctx, HostService_ListGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) ListPlatforms(ctx context.Context, in *HostListPlatformsRequest, opts ...grpc.CallOption) (*HostListPlatformsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostListPlatformsResponse)
	err := c.cc.Invoke(ctx, HostService_ListPlatforms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) ListModels(ctx context.Context, in *HostListModelsRequest, opts ...grpc.CallOption) (*HostListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostListModelsResponse)
	err := c.cc.Invoke(ctx, HostService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) GetUserInfo(ctx context.Context, in *HostGetUserInfoRequest, opts ...grpc.CallOption) (*HostGetUserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostGetUserInfoResponse)
	err := c.cc.Invoke(ctx, HostService_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServiceServer is the server API for HostService service.
// All implementations must embed UnimplementedHostServiceServer
// for forward compatibility.
type HostServiceServer interface {
	// 选号：根据 (group_id, model) 走和真实用户请求完全相同的调度路径。
	SelectAccount(context.Context, *HostSelectAccountRequest) (*HostSelectAccountResponse, error)
	// 把账号调用结果反馈给 scheduler 的失败计数器/状态机。
	ReportAccountResult(context.Context, *HostReportAccountResultRequest) (*Empty, error)
	// 黑盒探测：内部组装一次最小的 chat completion 请求并直接执行。
	// 跳过 usage_log 写入、跳过用户余额扣款，仍然 ReportResult 反哺账号状态机。
	ProbeForward(context.Context, *HostProbeForwardRequest) (*HostProbeForwardResponse, error)
	// 非流式业务转发：走完整管线（调度 → 网关插件 → 计费 → usage_log）。
	// 调用方需提供 user_id + group_id 以确定计费主体和调度路径。
	Forward(context.Context, *HostForwardRequest) (*HostForwardResponse, error)
	// 流式业务转发：与 Forward 相同管线，结果通过 server stream 逐块返回。
	// 最后一块 done=true 携带 usage 信息（计费已在 Core 侧完成）。
	ForwardStream(*HostForwardRequest, grpc.ServerStreamingServer[HostForwardChunk]) error
	// 列出所有分组。
	ListGroups(context.Context, *HostListGroupsRequest) (*HostListGroupsResponse, error)
	// 列出已加载的网关平台（每个 gateway 插件对应一个 platform）。
	ListPlatforms(context.Context, *HostListPlatformsRequest) (*HostListPlatformsResponse, error)
	// 列出指定平台的模型列表。
	ListModels(context.Context, *HostListModelsRequest) (*HostListModelsResponse, error)
	// 获取用户基本信息（余额、角色、状态）。
	GetUserInfo(context.Context, *HostGetUserInfoRequest) (*HostGetUserInfoResponse, error)
	mustEmbedUnimplementedHostServiceServer()
}

// UnimplementedHostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServiceServer struct{}

func (UnimplementedHostServiceServer) SelectAccount(context.Context, *HostSelectAccountRequest) (*HostSelectAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SelectAccount not implemented")
}
func (UnimplementedHostServiceServer) ReportAccountResult(context.Context, *HostReportAccountResultRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportAccountResult not implemented")
}
func (UnimplementedHostServiceServer) ProbeForward(context.Context, *HostProbeForwardRequest) (*HostProbeForwardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProbeForward not implemented")
}
func (UnimplementedHostServiceServer) Forward(context.Context, *HostForwardRequest) (*HostForwardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedHostServiceServer) ForwardStream(*HostForwardRequest, grpc.ServerStreamingServer[HostForwardChunk]) error {
	return status.Error(codes.Unimplemented, "method ForwardStream not implemented")
}
func (UnimplementedHostServiceServer) ListGroups(context.Context, *HostListGroupsRequest) (*HostListGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGroups not implemented")
}
func (UnimplementedHostServiceServer) ListPlatforms(context.Context, *HostListPlatformsRequest) (*HostListPlatformsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlatforms not implemented")
}
func (UnimplementedHostServiceServer) ListModels(context.Context, *HostListModelsRequest) (*HostListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedHostServiceServer) GetUserInfo(context.Context, *HostGetUserInfoRequest) (*HostGetUserInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedHostServiceServer) mustEmbedUnimplementedHostServiceServer() {}
func (UnimplementedHostServiceServer) testEmbeddedByValue()                     {}

// UnsafeHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServiceServer will
// result in compilation errors.
type UnsafeHostServiceServer interface {
	mustEmbedUnimplementedHostServiceServer()
}

func RegisterHostServiceServer(s grpc.ServiceRegistrar, srv HostServiceServer) {
	// If the following call panics, it indicates UnimplementedHostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostService_ServiceDesc, srv)
}

func _HostService_SelectAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostSelectAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).SelectAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_SelectAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).SelectAccount(ctx, req.(*HostSelectAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_ReportAccountResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostReportAccountResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).ReportAccountResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_ReportAccountResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).ReportAccountResult(ctx, req.(*HostReportAccountResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_ProbeForward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostProbeForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).ProbeForward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_ProbeForward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).ProbeForward(ctx, req.(*HostProbeForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_Forward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Forward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_Forward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Forward(ctx, req.(*HostForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_ForwardStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HostForwardRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HostServiceServer).ForwardStream(m, &grpc.GenericServerStream[HostForwardRequest, HostForwardChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostService_ForwardStreamServer = grpc.ServerStreamingServer[HostForwardChunk]

func _HostService_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_ListGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).ListGroups(ctx, req.(*HostListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_ListPlatforms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostListPlatformsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).ListPlatforms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_ListPlatforms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).ListPlatforms(ctx, req.(*HostListPlatformsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).ListModels(ctx, req.(*HostListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostGetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).GetUserInfo(ctx, req.(*HostGetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostService_ServiceDesc is the grpc.ServiceDesc for HostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "airgate.plugin.v1.HostService",
	HandlerType: (*HostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectAccount",
			Handler:    _HostService_SelectAccount_Handler,
		},
		{
			MethodName: "ReportAccountResult",
			Handler:    _HostService_ReportAccountResult_Handler,
		},
		{
			MethodName: "ProbeForward",
			Handler:    _HostService_ProbeForward_Handler,
		},
		{
			MethodName: "Forward",
			Handler:    _HostService_Forward_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _HostService_ListGroups_Handler,
		},
		{
			MethodName: "ListPlatforms",
			Handler:    _HostService_ListPlatforms_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _HostService_ListModels_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _HostService_GetUserInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ForwardStream",
			Handler:       _HostService_ForwardStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}
