// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.5
// source: plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginService_GetInfo_FullMethodName       = "/airgate.plugin.v2.PluginService/GetInfo"
	PluginService_Init_FullMethodName          = "/airgate.plugin.v2.PluginService/Init"
	PluginService_Start_FullMethodName         = "/airgate.plugin.v2.PluginService/Start"
	PluginService_Stop_FullMethodName          = "/airgate.plugin.v2.PluginService/Stop"
	PluginService_GetWebAssets_FullMethodName  = "/airgate.plugin.v2.PluginService/GetWebAssets"
	PluginService_GetSchema_FullMethodName     = "/airgate.plugin.v2.PluginService/GetSchema"
	PluginService_HealthCheck_FullMethodName   = "/airgate.plugin.v2.PluginService/HealthCheck"
	PluginService_HandleRequest_FullMethodName = "/airgate.plugin.v2.PluginService/HandleRequest"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginServiceClient interface {
	GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfoResponse, error)
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*Empty, error)
	Start(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// 获取插件的前端静态资源
	GetWebAssets(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WebAssetsResponse, error)
	// 获取插件结构化能力清单（可选，未实现时返回空）
	GetSchema(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginSchemaResponse, error)
	// 健康检查（可选，插件未实现时返回成功）
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// 通用请求代理：Core 透传，插件自行路由（可选，插件未实现时返回 501）
	HandleRequest(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfoResponse)
	err := c.cc.Invoke(ctx, PluginService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PluginService_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Start(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PluginService_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PluginService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) GetWebAssets(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WebAssetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebAssetsResponse)
	err := c.cc.Invoke(ctx, PluginService_GetWebAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) GetSchema(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginSchemaResponse)
	err := c.cc.Invoke(ctx, PluginService_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PluginService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) HandleRequest(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HttpResponse)
	err := c.cc.Invoke(ctx, PluginService_HandleRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility.
type PluginServiceServer interface {
	GetInfo(context.Context, *Empty) (*PluginInfoResponse, error)
	Init(context.Context, *InitRequest) (*Empty, error)
	Start(context.Context, *Empty) (*Empty, error)
	Stop(context.Context, *Empty) (*Empty, error)
	// 获取插件的前端静态资源
	GetWebAssets(context.Context, *Empty) (*WebAssetsResponse, error)
	// 获取插件结构化能力清单（可选，未实现时返回空）
	GetSchema(context.Context, *Empty) (*PluginSchemaResponse, error)
	// 健康检查（可选，插件未实现时返回成功）
	HealthCheck(context.Context, *Empty) (*Empty, error)
	// 通用请求代理：Core 透传，插件自行路由（可选，插件未实现时返回 501）
	HandleRequest(context.Context, *HttpRequest) (*HttpResponse, error)
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServiceServer struct{}

func (UnimplementedPluginServiceServer) GetInfo(context.Context, *Empty) (*PluginInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedPluginServiceServer) Init(context.Context, *InitRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedPluginServiceServer) Start(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedPluginServiceServer) Stop(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedPluginServiceServer) GetWebAssets(context.Context, *Empty) (*WebAssetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWebAssets not implemented")
}
func (UnimplementedPluginServiceServer) GetSchema(context.Context, *Empty) (*PluginSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedPluginServiceServer) HealthCheck(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPluginServiceServer) HandleRequest(context.Context, *HttpRequest) (*HttpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleRequest not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}
func (UnimplementedPluginServiceServer) testEmbeddedByValue()                       {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Start(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_GetWebAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetWebAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetWebAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetWebAssets(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetSchema(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_HandleRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).HandleRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_HandleRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).HandleRequest(ctx, req.(*HttpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "airgate.plugin.v2.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _PluginService_GetInfo_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _PluginService_Init_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _PluginService_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _PluginService_Stop_Handler,
		},
		{
			MethodName: "GetWebAssets",
			Handler:    _PluginService_GetWebAssets_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _PluginService_GetSchema_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PluginService_HealthCheck_Handler,
		},
		{
			MethodName: "HandleRequest",
			Handler:    _PluginService_HandleRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	GatewayService_GetPlatform_FullMethodName     = "/airgate.plugin.v2.GatewayService/GetPlatform"
	GatewayService_GetModels_FullMethodName       = "/airgate.plugin.v2.GatewayService/GetModels"
	GatewayService_GetRoutes_FullMethodName       = "/airgate.plugin.v2.GatewayService/GetRoutes"
	GatewayService_Forward_FullMethodName         = "/airgate.plugin.v2.GatewayService/Forward"
	GatewayService_ForwardStream_FullMethodName   = "/airgate.plugin.v2.GatewayService/ForwardStream"
	GatewayService_ValidateAccount_FullMethodName = "/airgate.plugin.v2.GatewayService/ValidateAccount"
	GatewayService_HandleWebSocket_FullMethodName = "/airgate.plugin.v2.GatewayService/HandleWebSocket"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayServiceClient interface {
	GetPlatform(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error)
	GetModels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModelsResponse, error)
	GetRoutes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RoutesResponse, error)
	Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardOutcome, error)
	ForwardStream(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ForwardChunk], error)
	ValidateAccount(ctx context.Context, in *CredentialsRequest, opts ...grpc.CallOption) (*Empty, error)
	// WebSocket 双向流
	HandleWebSocket(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WebSocketFrame, WebSocketFrame], error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) GetPlatform(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetPlatform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetModels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelsResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetRoutes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutesResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardOutcome, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardOutcome)
	err := c.cc.Invoke(ctx, GatewayService_Forward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ForwardStream(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ForwardChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayService_ServiceDesc.Streams[0], GatewayService_ForwardStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ForwardRequest, ForwardChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_ForwardStreamClient = grpc.ServerStreamingClient[ForwardChunk]

func (c *gatewayServiceClient) ValidateAccount(ctx context.Context, in *CredentialsRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GatewayService_ValidateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) HandleWebSocket(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WebSocketFrame, WebSocketFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayService_ServiceDesc.Streams[1], GatewayService_HandleWebSocket_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WebSocketFrame, WebSocketFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_HandleWebSocketClient = grpc.BidiStreamingClient[WebSocketFrame, WebSocketFrame]

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
type GatewayServiceServer interface {
	GetPlatform(context.Context, *Empty) (*StringResponse, error)
	GetModels(context.Context, *Empty) (*ModelsResponse, error)
	GetRoutes(context.Context, *Empty) (*RoutesResponse, error)
	Forward(context.Context, *ForwardRequest) (*ForwardOutcome, error)
	ForwardStream(*ForwardRequest, grpc.ServerStreamingServer[ForwardChunk]) error
	ValidateAccount(context.Context, *CredentialsRequest) (*Empty, error)
	// WebSocket 双向流
	HandleWebSocket(grpc.BidiStreamingServer[WebSocketFrame, WebSocketFrame]) error
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) GetPlatform(context.Context, *Empty) (*StringResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlatform not implemented")
}
func (UnimplementedGatewayServiceServer) GetModels(context.Context, *Empty) (*ModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModels not implemented")
}
func (UnimplementedGatewayServiceServer) GetRoutes(context.Context, *Empty) (*RoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoutes not implemented")
}
func (UnimplementedGatewayServiceServer) Forward(context.Context, *ForwardRequest) (*ForwardOutcome, error) {
	return nil, status.Error(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedGatewayServiceServer) ForwardStream(*ForwardRequest, grpc.ServerStreamingServer[ForwardChunk]) error {
	return status.Error(codes.Unimplemented, "method ForwardStream not implemented")
}
func (UnimplementedGatewayServiceServer) ValidateAccount(context.Context, *CredentialsRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateAccount not implemented")
}
func (UnimplementedGatewayServiceServer) HandleWebSocket(grpc.BidiStreamingServer[WebSocketFrame, WebSocketFrame]) error {
	return status.Error(codes.Unimplemented, "method HandleWebSocket not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_GetPlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetPlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetPlatform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetPlatform(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetModels(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetRoutes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_Forward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).Forward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_Forward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).Forward(ctx, req.(*ForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ForwardStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ForwardRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayServiceServer).ForwardStream(m, &grpc.GenericServerStream[ForwardRequest, ForwardChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_ForwardStreamServer = grpc.ServerStreamingServer[ForwardChunk]

func _GatewayService_ValidateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ValidateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ValidateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ValidateAccount(ctx, req.(*CredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_HandleWebSocket_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayServiceServer).HandleWebSocket(&grpc.GenericServerStream[WebSocketFrame, WebSocketFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_HandleWebSocketServer = grpc.BidiStreamingServer[WebSocketFrame, WebSocketFrame]

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "airgate.plugin.v2.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlatform",
			Handler:    _GatewayService_GetPlatform_Handler,
		},
		{
			MethodName: "GetModels",
			Handler:    _GatewayService_GetModels_Handler,
		},
		{
			MethodName: "GetRoutes",
			Handler:    _GatewayService_GetRoutes_Handler,
		},
		{
			MethodName: "Forward",
			Handler:    _GatewayService_Forward_Handler,
		},
		{
			MethodName: "ValidateAccount",
			Handler:    _GatewayService_ValidateAccount_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ForwardStream",
			Handler:       _GatewayService_ForwardStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "HandleWebSocket",
			Handler:       _GatewayService_HandleWebSocket_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

const (
	ExtensionService_Migrate_FullMethodName             = "/airgate.plugin.v2.ExtensionService/Migrate"
	ExtensionService_GetBackgroundTasks_FullMethodName  = "/airgate.plugin.v2.ExtensionService/GetBackgroundTasks"
	ExtensionService_RunBackgroundTask_FullMethodName   = "/airgate.plugin.v2.ExtensionService/RunBackgroundTask"
	ExtensionService_HandleRequest_FullMethodName       = "/airgate.plugin.v2.ExtensionService/HandleRequest"
	ExtensionService_HandleStreamRequest_FullMethodName = "/airgate.plugin.v2.ExtensionService/HandleStreamRequest"
	ExtensionService_ProcessTask_FullMethodName         = "/airgate.plugin.v2.ExtensionService/ProcessTask"
	ExtensionService_GetTaskTypes_FullMethodName        = "/airgate.plugin.v2.ExtensionService/GetTaskTypes"
)

// ExtensionServiceClient is the client API for ExtensionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExtensionServiceClient interface {
	Migrate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	GetBackgroundTasks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BackgroundTasksResponse, error)
	// 由 Core 调度器按 Interval 周期触发；插件进程内查表执行 Handler
	RunBackgroundTask(ctx context.Context, in *RunBackgroundTaskRequest, opts ...grpc.CallOption) (*Empty, error)
	// HTTP 请求由核心代理到插件
	HandleRequest(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error)
	HandleStreamRequest(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HttpResponseChunk], error)
	// 异步任务：Core 分发 pending 任务给插件处理
	ProcessTask(ctx context.Context, in *ProcessTaskRequest, opts ...grpc.CallOption) (*ProcessTaskResponse, error)
	// 返回此插件支持的任务类型列表
	GetTaskTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaskTypesResponse, error)
}

type extensionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExtensionServiceClient(cc grpc.ClientConnInterface) ExtensionServiceClient {
	return &extensionServiceClient{cc}
}

func (c *extensionServiceClient) Migrate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ExtensionService_Migrate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) GetBackgroundTasks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BackgroundTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackgroundTasksResponse)
	err := c.cc.Invoke(ctx, ExtensionService_GetBackgroundTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) RunBackgroundTask(ctx context.Context, in *RunBackgroundTaskRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ExtensionService_RunBackgroundTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) HandleRequest(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HttpResponse)
	err := c.cc.Invoke(ctx, ExtensionService_HandleRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) HandleStreamRequest(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HttpResponseChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExtensionService_ServiceDesc.Streams[0], ExtensionService_HandleStreamRequest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HttpRequest, HttpResponseChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExtensionService_HandleStreamRequestClient = grpc.ServerStreamingClient[HttpResponseChunk]

func (c *extensionServiceClient) ProcessTask(ctx context.Context, in *ProcessTaskRequest, opts ...grpc.CallOption) (*ProcessTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessTaskResponse)
	err := c.cc.Invoke(ctx, ExtensionService_ProcessTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) GetTaskTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaskTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskTypesResponse)
	err := c.cc.Invoke(ctx, ExtensionService_GetTaskTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtensionServiceServer is the server API for ExtensionService service.
// All implementations must embed UnimplementedExtensionServiceServer
// for forward compatibility.
type ExtensionServiceServer interface {
	Migrate(context.Context, *Empty) (*Empty, error)
	GetBackgroundTasks(context.Context, *Empty) (*BackgroundTasksResponse, error)
	// 由 Core 调度器按 Interval 周期触发；插件进程内查表执行 Handler
	RunBackgroundTask(context.Context, *RunBackgroundTaskRequest) (*Empty, error)
	// HTTP 请求由核心代理到插件
	HandleRequest(context.Context, *HttpRequest) (*HttpResponse, error)
	HandleStreamRequest(*HttpRequest, grpc.ServerStreamingServer[HttpResponseChunk]) error
	// 异步任务：Core 分发 pending 任务给插件处理
	ProcessTask(context.Context, *ProcessTaskRequest) (*ProcessTaskResponse, error)
	// 返回此插件支持的任务类型列表
	GetTaskTypes(context.Context, *Empty) (*TaskTypesResponse, error)
	mustEmbedUnimplementedExtensionServiceServer()
}

// UnimplementedExtensionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExtensionServiceServer struct{}

func (UnimplementedExtensionServiceServer) Migrate(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Migrate not implemented")
}
func (UnimplementedExtensionServiceServer) GetBackgroundTasks(context.Context, *Empty) (*BackgroundTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBackgroundTasks not implemented")
}
func (UnimplementedExtensionServiceServer) RunBackgroundTask(context.Context, *RunBackgroundTaskRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RunBackgroundTask not implemented")
}
func (UnimplementedExtensionServiceServer) HandleRequest(context.Context, *HttpRequest) (*HttpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleRequest not implemented")
}
func (UnimplementedExtensionServiceServer) HandleStreamRequest(*HttpRequest, grpc.ServerStreamingServer[HttpResponseChunk]) error {
	return status.Error(codes.Unimplemented, "method HandleStreamRequest not implemented")
}
func (UnimplementedExtensionServiceServer) ProcessTask(context.Context, *ProcessTaskRequest) (*ProcessTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessTask not implemented")
}
func (UnimplementedExtensionServiceServer) GetTaskTypes(context.Context, *Empty) (*TaskTypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskTypes not implemented")
}
func (UnimplementedExtensionServiceServer) mustEmbedUnimplementedExtensionServiceServer() {}
func (UnimplementedExtensionServiceServer) testEmbeddedByValue()                          {}

// UnsafeExtensionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtensionServiceServer will
// result in compilation errors.
type UnsafeExtensionServiceServer interface {
	mustEmbedUnimplementedExtensionServiceServer()
}

func RegisterExtensionServiceServer(s grpc.ServiceRegistrar, srv ExtensionServiceServer) {
	// If the following call panics, it indicates UnimplementedExtensionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExtensionService_ServiceDesc, srv)
}

func _ExtensionService_Migrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).Migrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_Migrate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).Migrate(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_GetBackgroundTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).GetBackgroundTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_GetBackgroundTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).GetBackgroundTasks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_RunBackgroundTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunBackgroundTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).RunBackgroundTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_RunBackgroundTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).RunBackgroundTask(ctx, req.(*RunBackgroundTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_HandleRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).HandleRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_HandleRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).HandleRequest(ctx, req.(*HttpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_HandleStreamRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HttpRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExtensionServiceServer).HandleStreamRequest(m, &grpc.GenericServerStream[HttpRequest, HttpResponseChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExtensionService_HandleStreamRequestServer = grpc.ServerStreamingServer[HttpResponseChunk]

func _ExtensionService_ProcessTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).ProcessTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_ProcessTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).ProcessTask(ctx, req.(*ProcessTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_GetTaskTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).GetTaskTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_GetTaskTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).GetTaskTypes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ExtensionService_ServiceDesc is the grpc.ServiceDesc for ExtensionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExtensionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "airgate.plugin.v2.ExtensionService",
	HandlerType: (*ExtensionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Migrate",
			Handler:    _ExtensionService_Migrate_Handler,
		},
		{
			MethodName: "GetBackgroundTasks",
			Handler:    _ExtensionService_GetBackgroundTasks_Handler,
		},
		{
			MethodName: "RunBackgroundTask",
			Handler:    _ExtensionService_RunBackgroundTask_Handler,
		},
		{
			MethodName: "HandleRequest",
			Handler:    _ExtensionService_HandleRequest_Handler,
		},
		{
			MethodName: "ProcessTask",
			Handler:    _ExtensionService_ProcessTask_Handler,
		},
		{
			MethodName: "GetTaskTypes",
			Handler:    _ExtensionService_GetTaskTypes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HandleStreamRequest",
			Handler:       _ExtensionService_HandleStreamRequest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

const (
	MiddlewareService_OnForwardBegin_FullMethodName = "/airgate.plugin.v2.MiddlewareService/OnForwardBegin"
	MiddlewareService_OnForwardEnd_FullMethodName   = "/airgate.plugin.v2.MiddlewareService/OnForwardEnd"
)

// MiddlewareServiceClient is the client API for MiddlewareService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== 中间件服务（Core → Plugin，forward 路径拦截） ====================
//
// MiddlewareService 让"请求中间层"这种旁路插件能拿到每次 forward 的前后事件：
//   - OnForwardBegin  — 选完账号 / 还没调 upstream 之前，能改 headers / 拒绝请求
//   - OnForwardEnd    — upstream 返回之后 / 写 usage_log 之前，拿到完整 metadata
//
// 设计原则：
//  1. middleware 挂了不能 block 生产：返回 error 只 log warn，流程继续；
//     只有 OnForwardBegin 明确返回 Action=DENY 才会拒绝请求
//  2. 多个 middleware 按 priority 排序。Begin 升序、End 降序（LIFO）
//  3. payload 两段式：默认只传元数据，声明 middleware.read_body capability 的插件
//     才会收到 request_body / response_body
//  4. 流式响应的 response_body 只给摘要（首次非空 chunk 拼装），完整流式内容应由
//     独立的流式事件能力承载
//
// 新角色：middleware 插件不是 gateway（不替代 upstream），也不是 extension
// （不跑后台任务 + 自定义 HTTP）。它在 PluginInfo.type = "middleware" 中声明。
type MiddlewareServiceClient interface {
	OnForwardBegin(ctx context.Context, in *MiddlewareRequest, opts ...grpc.CallOption) (*MiddlewareDecision, error)
	OnForwardEnd(ctx context.Context, in *MiddlewareEvent, opts ...grpc.CallOption) (*Empty, error)
}

type middlewareServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMiddlewareServiceClient(cc grpc.ClientConnInterface) MiddlewareServiceClient {
	return &middlewareServiceClient{cc}
}

func (c *middlewareServiceClient) OnForwardBegin(ctx context.Context, in *MiddlewareRequest, opts ...grpc.CallOption) (*MiddlewareDecision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MiddlewareDecision)
	err := c.cc.Invoke(ctx, MiddlewareService_OnForwardBegin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareServiceClient) OnForwardEnd(ctx context.Context, in *MiddlewareEvent, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MiddlewareService_OnForwardEnd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiddlewareServiceServer is the server API for MiddlewareService service.
// All implementations must embed UnimplementedMiddlewareServiceServer
// for forward compatibility.
//
// ==================== 中间件服务（Core → Plugin，forward 路径拦截） ====================
//
// MiddlewareService 让"请求中间层"这种旁路插件能拿到每次 forward 的前后事件：
//   - OnForwardBegin  — 选完账号 / 还没调 upstream 之前，能改 headers / 拒绝请求
//   - OnForwardEnd    — upstream 返回之后 / 写 usage_log 之前，拿到完整 metadata
//
// 设计原则：
//  1. middleware 挂了不能 block 生产：返回 error 只 log warn，流程继续；
//     只有 OnForwardBegin 明确返回 Action=DENY 才会拒绝请求
//  2. 多个 middleware 按 priority 排序。Begin 升序、End 降序（LIFO）
//  3. payload 两段式：默认只传元数据，声明 middleware.read_body capability 的插件
//     才会收到 request_body / response_body
//  4. 流式响应的 response_body 只给摘要（首次非空 chunk 拼装），完整流式内容应由
//     独立的流式事件能力承载
//
// 新角色：middleware 插件不是 gateway（不替代 upstream），也不是 extension
// （不跑后台任务 + 自定义 HTTP）。它在 PluginInfo.type = "middleware" 中声明。
type MiddlewareServiceServer interface {
	OnForwardBegin(context.Context, *MiddlewareRequest) (*MiddlewareDecision, error)
	OnForwardEnd(context.Context, *MiddlewareEvent) (*Empty, error)
	mustEmbedUnimplementedMiddlewareServiceServer()
}

// UnimplementedMiddlewareServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMiddlewareServiceServer struct{}

func (UnimplementedMiddlewareServiceServer) OnForwardBegin(context.Context, *MiddlewareRequest) (*MiddlewareDecision, error) {
	return nil, status.Error(codes.Unimplemented, "method OnForwardBegin not implemented")
}
func (UnimplementedMiddlewareServiceServer) OnForwardEnd(context.Context, *MiddlewareEvent) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnForwardEnd not implemented")
}
func (UnimplementedMiddlewareServiceServer) mustEmbedUnimplementedMiddlewareServiceServer() {}
func (UnimplementedMiddlewareServiceServer) testEmbeddedByValue()                           {}

// UnsafeMiddlewareServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MiddlewareServiceServer will
// result in compilation errors.
type UnsafeMiddlewareServiceServer interface {
	mustEmbedUnimplementedMiddlewareServiceServer()
}

func RegisterMiddlewareServiceServer(s grpc.ServiceRegistrar, srv MiddlewareServiceServer) {
	// If the following call panics, it indicates UnimplementedMiddlewareServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MiddlewareService_ServiceDesc, srv)
}

func _MiddlewareService_OnForwardBegin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MiddlewareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewareServiceServer).OnForwardBegin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiddlewareService_OnForwardBegin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewareServiceServer).OnForwardBegin(ctx, req.(*MiddlewareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiddlewareService_OnForwardEnd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MiddlewareEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewareServiceServer).OnForwardEnd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiddlewareService_OnForwardEnd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewareServiceServer).OnForwardEnd(ctx, req.(*MiddlewareEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// MiddlewareService_ServiceDesc is the grpc.ServiceDesc for MiddlewareService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MiddlewareService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "airgate.plugin.v2.MiddlewareService",
	HandlerType: (*MiddlewareServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnForwardBegin",
			Handler:    _MiddlewareService_OnForwardBegin_Handler,
		},
		{
			MethodName: "OnForwardEnd",
			Handler:    _MiddlewareService_OnForwardEnd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	EventService_GetEventSubscriptions_FullMethodName = "/airgate.plugin.v2.EventService/GetEventSubscriptions"
	EventService_HandleEvent_FullMethodName           = "/airgate.plugin.v2.EventService/HandleEvent"
)

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventServiceClient interface {
	GetEventSubscriptions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EventSubscriptionsResponse, error)
	HandleEvent(ctx context.Context, in *PluginEvent, opts ...grpc.CallOption) (*EventHandleResponse, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) GetEventSubscriptions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EventSubscriptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventSubscriptionsResponse)
	err := c.cc.Invoke(ctx, EventService_GetEventSubscriptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) HandleEvent(ctx context.Context, in *PluginEvent, opts ...grpc.CallOption) (*EventHandleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventHandleResponse)
	err := c.cc.Invoke(ctx, EventService_HandleEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
// All implementations must embed UnimplementedEventServiceServer
// for forward compatibility.
type EventServiceServer interface {
	GetEventSubscriptions(context.Context, *Empty) (*EventSubscriptionsResponse, error)
	HandleEvent(context.Context, *PluginEvent) (*EventHandleResponse, error)
	mustEmbedUnimplementedEventServiceServer()
}

// UnimplementedEventServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventServiceServer struct{}

func (UnimplementedEventServiceServer) GetEventSubscriptions(context.Context, *Empty) (*EventSubscriptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventSubscriptions not implemented")
}
func (UnimplementedEventServiceServer) HandleEvent(context.Context, *PluginEvent) (*EventHandleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleEvent not implemented")
}
func (UnimplementedEventServiceServer) mustEmbedUnimplementedEventServiceServer() {}
func (UnimplementedEventServiceServer) testEmbeddedByValue()                      {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	// If the following call panics, it indicates UnimplementedEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_GetEventSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEventSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEventSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEventSubscriptions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_HandleEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).HandleEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_HandleEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).HandleEvent(ctx, req.(*PluginEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "airgate.plugin.v2.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEventSubscriptions",
			Handler:    _EventService_GetEventSubscriptions_Handler,
		},
		{
			MethodName: "HandleEvent",
			Handler:    _EventService_HandleEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	CoreInvokeService_Invoke_FullMethodName       = "/airgate.plugin.v2.CoreInvokeService/Invoke"
	CoreInvokeService_InvokeStream_FullMethodName = "/airgate.plugin.v2.CoreInvokeService/InvokeStream"
)

// CoreInvokeServiceClient is the client API for CoreInvokeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== Host 服务（反向调用：插件 → Core） ====================
//
// 由 Core 实现，通过 hashicorp/go-plugin 的 GRPCBroker 暴露给插件子进程。
// SDK 只定义通用 Invoke / InvokeStream 通道；Core 通过方法注册表决定开放哪些方法、
// 允许哪些插件调用、请求/响应 schema、是否支持流式以及幂等策略。
type CoreInvokeServiceClient interface {
	Invoke(ctx context.Context, in *HostInvokeRequest, opts ...grpc.CallOption) (*HostInvokeResponse, error)
	InvokeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HostStreamFrame, HostStreamFrame], error)
}

type coreInvokeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreInvokeServiceClient(cc grpc.ClientConnInterface) CoreInvokeServiceClient {
	return &coreInvokeServiceClient{cc}
}

func (c *coreInvokeServiceClient) Invoke(ctx context.Context, in *HostInvokeRequest, opts ...grpc.CallOption) (*HostInvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostInvokeResponse)
	err := c.cc.Invoke(ctx, CoreInvokeService_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreInvokeServiceClient) InvokeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HostStreamFrame, HostStreamFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoreInvokeService_ServiceDesc.Streams[0], CoreInvokeService_InvokeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HostStreamFrame, HostStreamFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoreInvokeService_InvokeStreamClient = grpc.BidiStreamingClient[HostStreamFrame, HostStreamFrame]

// CoreInvokeServiceServer is the server API for CoreInvokeService service.
// All implementations must embed UnimplementedCoreInvokeServiceServer
// for forward compatibility.
//
// ==================== Host 服务（反向调用：插件 → Core） ====================
//
// 由 Core 实现，通过 hashicorp/go-plugin 的 GRPCBroker 暴露给插件子进程。
// SDK 只定义通用 Invoke / InvokeStream 通道；Core 通过方法注册表决定开放哪些方法、
// 允许哪些插件调用、请求/响应 schema、是否支持流式以及幂等策略。
type CoreInvokeServiceServer interface {
	Invoke(context.Context, *HostInvokeRequest) (*HostInvokeResponse, error)
	InvokeStream(grpc.BidiStreamingServer[HostStreamFrame, HostStreamFrame]) error
	mustEmbedUnimplementedCoreInvokeServiceServer()
}

// UnimplementedCoreInvokeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreInvokeServiceServer struct{}

func (UnimplementedCoreInvokeServiceServer) Invoke(context.Context, *HostInvokeRequest) (*HostInvokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedCoreInvokeServiceServer) InvokeStream(grpc.BidiStreamingServer[HostStreamFrame, HostStreamFrame]) error {
	return status.Error(codes.Unimplemented, "method InvokeStream not implemented")
}
func (UnimplementedCoreInvokeServiceServer) mustEmbedUnimplementedCoreInvokeServiceServer() {}
func (UnimplementedCoreInvokeServiceServer) testEmbeddedByValue()                           {}

// UnsafeCoreInvokeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreInvokeServiceServer will
// result in compilation errors.
type UnsafeCoreInvokeServiceServer interface {
	mustEmbedUnimplementedCoreInvokeServiceServer()
}

func RegisterCoreInvokeServiceServer(s grpc.ServiceRegistrar, srv CoreInvokeServiceServer) {
	// If the following call panics, it indicates UnimplementedCoreInvokeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreInvokeService_ServiceDesc, srv)
}

func _CoreInvokeService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostInvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreInvokeServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreInvokeService_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreInvokeServiceServer).Invoke(ctx, req.(*HostInvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreInvokeService_InvokeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CoreInvokeServiceServer).InvokeStream(&grpc.GenericServerStream[HostStreamFrame, HostStreamFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoreInvokeService_InvokeStreamServer = grpc.BidiStreamingServer[HostStreamFrame, HostStreamFrame]

// CoreInvokeService_ServiceDesc is the grpc.ServiceDesc for CoreInvokeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreInvokeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "airgate.plugin.v2.CoreInvokeService",
	HandlerType: (*CoreInvokeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _CoreInvokeService_Invoke_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InvokeStream",
			Handler:       _CoreInvokeService_InvokeStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plugin.proto",
}
